export const APP_NAME = 'Softkey Android'
export const PRIMARY_COLOR = '#fA0'

export const ACTION_ADD_IP = "ACTION_ADD_IP";
export const ACTION_ADD_PORT = "ACTION_ADD_PORT";
export const ACTION_ADD_CHANNEL = "ACTION_ADD_CHANNEL";
export const ACTION_ERROR_PORT = "ACTION_ERROR_PORT";
export const ACTION_ERROR_PORT_MESSAGE = "ACTION_ERROR_PORT_MESSAGE";
export const ACTION_ERROR_CHANNEL = "ACTION_ERROR_CHANNEL";
export const ACTION_ERROR_CHANNEL_MESSAGE = "ACTION_ERROR_CHANNEL_MESSAGE";
